// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/price_monitoring.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_proto_price_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_proto_price_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckItemRequest) Reset() {
	*x = CheckItemRequest{}
	mi := &file_proto_price_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemRequest) ProtoMessage() {}

func (x *CheckItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemRequest.ProtoReflect.Descriptor instead.
func (*CheckItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *CheckItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckItemRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type CheckItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	LastChecked   string                 `protobuf:"bytes,4,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckItemResponse) Reset() {
	*x = CheckItemResponse{}
	mi := &file_proto_price_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckItemResponse) ProtoMessage() {}

func (x *CheckItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckItemResponse.ProtoReflect.Descriptor instead.
func (*CheckItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *CheckItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckItemResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CheckItemResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CheckItemResponse) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

func (x *CheckItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsRequest) Reset() {
	*x = GetAllItemsRequest{}
	mi := &file_proto_price_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsRequest) ProtoMessage() {}

func (x *GetAllItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	LastChecked   string                 `protobuf:"bytes,3,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"` // Добавлено это поле
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_price_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Item) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Item) GetLastChecked() string {
	if x != nil {
		return x.LastChecked
	}
	return ""
}

type GetAllItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsResponse) Reset() {
	*x = GetAllItemsResponse{}
	mi := &file_proto_price_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsResponse) ProtoMessage() {}

func (x *GetAllItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetAllItemsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistoryRequest) Reset() {
	*x = PriceHistoryRequest{}
	mi := &file_proto_price_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistoryRequest) ProtoMessage() {}

func (x *PriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*PriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *PriceHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PriceHistoryRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type PriceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceEntry) Reset() {
	*x = PriceEntry{}
	mi := &file_proto_price_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceEntry) ProtoMessage() {}

func (x *PriceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceEntry.ProtoReflect.Descriptor instead.
func (*PriceEntry) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *PriceEntry) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceEntry) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type PriceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	History       []*PriceEntry          `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistoryResponse) Reset() {
	*x = PriceHistoryResponse{}
	mi := &file_proto_price_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistoryResponse) ProtoMessage() {}

func (x *PriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*PriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *PriceHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PriceHistoryResponse) GetHistory() []*PriceEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *PriceHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllRequest) Reset() {
	*x = CheckAllRequest{}
	mi := &file_proto_price_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllRequest) ProtoMessage() {}

func (x *CheckAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllRequest.ProtoReflect.Descriptor instead.
func (*CheckAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{10}
}

type CheckAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAllResponse) Reset() {
	*x = CheckAllResponse{}
	mi := &file_proto_price_monitoring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAllResponse) ProtoMessage() {}

func (x *CheckAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_price_monitoring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAllResponse.ProtoReflect.Descriptor instead.
func (*CheckAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_price_monitoring_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckAllResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_price_monitoring_proto protoreflect.FileDescriptor

const file_proto_price_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/price_monitoring.proto\x12\x10price_monitoring\"=\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"E\n" +
	"\x0fAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x10CheckItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"\xa3\x01\n" +
	"\x11CheckItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice\x12!\n" +
	"\flast_checked\x18\x04 \x01(\tR\vlastChecked\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"-\n" +
	"\x12GetAllItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"b\n" +
	"\x04Item\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\x01R\fcurrentPrice\x12!\n" +
	"\flast_checked\x18\x03 \x01(\tR\vlastChecked\"w\n" +
	"\x13GetAllItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.price_monitoring.ItemR\x05items\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"B\n" +
	"\x13PriceHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"A\n" +
	"\n" +
	"PriceEntry\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\tR\tcheckedAt\"\x82\x01\n" +
	"\x14PriceHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\ahistory\x18\x02 \x03(\v2\x1c.price_monitoring.PriceEntryR\ahistory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x11\n" +
	"\x0fCheckAllRequest\"F\n" +
	"\x10CheckAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcf\x03\n" +
	"\x16PriceMonitoringService\x12N\n" +
	"\aAddItem\x12 .price_monitoring.AddItemRequest\x1a!.price_monitoring.AddItemResponse\x12T\n" +
	"\tCheckItem\x12\".price_monitoring.CheckItemRequest\x1a#.price_monitoring.CheckItemResponse\x12Z\n" +
	"\vGetAllItems\x12$.price_monitoring.GetAllItemsRequest\x1a%.price_monitoring.GetAllItemsResponse\x12`\n" +
	"\x0fGetPriceHistory\x12%.price_monitoring.PriceHistoryRequest\x1a&.price_monitoring.PriceHistoryResponse\x12Q\n" +
	"\bCheckAll\x12!.price_monitoring.CheckAllRequest\x1a\".price_monitoring.CheckAllResponseB'Z%github.com/gulovv/price-tracker/protob\x06proto3"

var (
	file_proto_price_monitoring_proto_rawDescOnce sync.Once
	file_proto_price_monitoring_proto_rawDescData []byte
)

func file_proto_price_monitoring_proto_rawDescGZIP() []byte {
	file_proto_price_monitoring_proto_rawDescOnce.Do(func() {
		file_proto_price_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_price_monitoring_proto_rawDesc), len(file_proto_price_monitoring_proto_rawDesc)))
	})
	return file_proto_price_monitoring_proto_rawDescData
}

var file_proto_price_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_price_monitoring_proto_goTypes = []any{
	(*AddItemRequest)(nil),       // 0: price_monitoring.AddItemRequest
	(*AddItemResponse)(nil),      // 1: price_monitoring.AddItemResponse
	(*CheckItemRequest)(nil),     // 2: price_monitoring.CheckItemRequest
	(*CheckItemResponse)(nil),    // 3: price_monitoring.CheckItemResponse
	(*GetAllItemsRequest)(nil),   // 4: price_monitoring.GetAllItemsRequest
	(*Item)(nil),                 // 5: price_monitoring.Item
	(*GetAllItemsResponse)(nil),  // 6: price_monitoring.GetAllItemsResponse
	(*PriceHistoryRequest)(nil),  // 7: price_monitoring.PriceHistoryRequest
	(*PriceEntry)(nil),           // 8: price_monitoring.PriceEntry
	(*PriceHistoryResponse)(nil), // 9: price_monitoring.PriceHistoryResponse
	(*CheckAllRequest)(nil),      // 10: price_monitoring.CheckAllRequest
	(*CheckAllResponse)(nil),     // 11: price_monitoring.CheckAllResponse
}
var file_proto_price_monitoring_proto_depIdxs = []int32{
	5,  // 0: price_monitoring.GetAllItemsResponse.items:type_name -> price_monitoring.Item
	8,  // 1: price_monitoring.PriceHistoryResponse.history:type_name -> price_monitoring.PriceEntry
	0,  // 2: price_monitoring.PriceMonitoringService.AddItem:input_type -> price_monitoring.AddItemRequest
	2,  // 3: price_monitoring.PriceMonitoringService.CheckItem:input_type -> price_monitoring.CheckItemRequest
	4,  // 4: price_monitoring.PriceMonitoringService.GetAllItems:input_type -> price_monitoring.GetAllItemsRequest
	7,  // 5: price_monitoring.PriceMonitoringService.GetPriceHistory:input_type -> price_monitoring.PriceHistoryRequest
	10, // 6: price_monitoring.PriceMonitoringService.CheckAll:input_type -> price_monitoring.CheckAllRequest
	1,  // 7: price_monitoring.PriceMonitoringService.AddItem:output_type -> price_monitoring.AddItemResponse
	3,  // 8: price_monitoring.PriceMonitoringService.CheckItem:output_type -> price_monitoring.CheckItemResponse
	6,  // 9: price_monitoring.PriceMonitoringService.GetAllItems:output_type -> price_monitoring.GetAllItemsResponse
	9,  // 10: price_monitoring.PriceMonitoringService.GetPriceHistory:output_type -> price_monitoring.PriceHistoryResponse
	11, // 11: price_monitoring.PriceMonitoringService.CheckAll:output_type -> price_monitoring.CheckAllResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_price_monitoring_proto_init() }
func file_proto_price_monitoring_proto_init() {
	if File_proto_price_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_price_monitoring_proto_rawDesc), len(file_proto_price_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_price_monitoring_proto_goTypes,
		DependencyIndexes: file_proto_price_monitoring_proto_depIdxs,
		MessageInfos:      file_proto_price_monitoring_proto_msgTypes,
	}.Build()
	File_proto_price_monitoring_proto = out.File
	file_proto_price_monitoring_proto_goTypes = nil
	file_proto_price_monitoring_proto_depIdxs = nil
}
