services:

  server:
    image: price_tracker
    build: .
    env_file:
      - ./internal/db/config.env
    ports:
      - 50051:50051
    depends_on:
      postgres:
        condition: service_healthy
      # chrome:
      #   condition: service_healthy

  postgres:
    image: postgres:16.0
    container_name: postgres_container
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: scraper
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "scraper"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - 5432:5432
    
  # chrome:
  #   image: selenium/standalone-chromium:latest
  #   container_name: chrome
  #   shm_size: 2gb
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   ports:
  #     - "4444:4444"