// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: price_tracker.proto

package price_monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartPrice    float32                `protobuf:"fixed32,2,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	CurrentPrice  float32                `protobuf:"fixed32,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	DiffPrice     float32                `protobuf:"fixed32,4,opt,name=diff_price,json=diffPrice,proto3" json:"diff_price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_price_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_price_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *ItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemResponse) GetStartPrice() float32 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *ItemResponse) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *ItemResponse) GetDiffPrice() float32 {
	if x != nil {
		return x.DiffPrice
	}
	return 0
}

func (x *ItemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_price_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_price_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *GetItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ItemResponse          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_price_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_price_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemResponse) GetItem() *ItemResponse {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetAllItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsRequest) Reset() {
	*x = GetAllItemsRequest{}
	mi := &file_price_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsRequest) ProtoMessage() {}

func (x *GetAllItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsRequest) Descriptor() ([]byte, []int) {
	return file_price_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemResponse        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsResponse) Reset() {
	*x = GetAllItemsResponse{}
	mi := &file_price_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsResponse) ProtoMessage() {}

func (x *GetAllItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return file_price_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllItemsResponse) GetItems() []*ItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_price_tracker_proto protoreflect.FileDescriptor

const file_price_tracker_proto_rawDesc = "" +
	"\n" +
	"\x13price_tracker.proto\x12\rprice_tracker\"\x9f\x01\n" +
	"\fItemResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vstart_price\x18\x02 \x01(\x02R\n" +
	"startPrice\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x02R\fcurrentPrice\x12\x1d\n" +
	"\n" +
	"diff_price\x18\x04 \x01(\x02R\tdiffPrice\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"=\n" +
	"\x0eGetItemRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x0fGetItemResponse\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.price_tracker.ItemResponseR\x04item\"-\n" +
	"\x12GetAllItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x13GetAllItemsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.price_tracker.ItemResponseR\x05items2\xa9\x01\n" +
	"\aScraper\x12H\n" +
	"\aGetItem\x12\x1d.price_tracker.GetItemRequest\x1a\x1e.price_tracker.GetItemResponse\x12T\n" +
	"\vGetAllItems\x12!.price_tracker.GetAllItemsRequest\x1a\".price_tracker.GetAllItemsResponseB\x15Z\x13price_tracker/protob\x06proto3"

var (
	file_price_tracker_proto_rawDescOnce sync.Once
	file_price_tracker_proto_rawDescData []byte
)

func file_price_tracker_proto_rawDescGZIP() []byte {
	file_price_tracker_proto_rawDescOnce.Do(func() {
		file_price_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_price_tracker_proto_rawDesc), len(file_price_tracker_proto_rawDesc)))
	})
	return file_price_tracker_proto_rawDescData
}

var file_price_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_price_tracker_proto_goTypes = []any{
	(*ItemResponse)(nil),        // 0: price_tracker.ItemResponse
	(*GetItemRequest)(nil),      // 1: price_tracker.GetItemRequest
	(*GetItemResponse)(nil),     // 2: price_tracker.GetItemResponse
	(*GetAllItemsRequest)(nil),  // 3: price_tracker.GetAllItemsRequest
	(*GetAllItemsResponse)(nil), // 4: price_tracker.GetAllItemsResponse
}
var file_price_tracker_proto_depIdxs = []int32{
	0, // 0: price_tracker.GetItemResponse.item:type_name -> price_tracker.ItemResponse
	0, // 1: price_tracker.GetAllItemsResponse.items:type_name -> price_tracker.ItemResponse
	1, // 2: price_tracker.Scraper.GetItem:input_type -> price_tracker.GetItemRequest
	3, // 3: price_tracker.Scraper.GetAllItems:input_type -> price_tracker.GetAllItemsRequest
	2, // 4: price_tracker.Scraper.GetItem:output_type -> price_tracker.GetItemResponse
	4, // 5: price_tracker.Scraper.GetAllItems:output_type -> price_tracker.GetAllItemsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_price_tracker_proto_init() }
func file_price_tracker_proto_init() {
	if File_price_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_price_tracker_proto_rawDesc), len(file_price_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_tracker_proto_goTypes,
		DependencyIndexes: file_price_tracker_proto_depIdxs,
		MessageInfos:      file_price_tracker_proto_msgTypes,
	}.Build()
	File_price_tracker_proto = out.File
	file_price_tracker_proto_goTypes = nil
	file_price_tracker_proto_depIdxs = nil
}
